import yt_dlp
import os

def download_youtube_as_mp3(url, download_folder):
    """
    Downloads a YouTube video as an MP3 and returns (file_name, file_path).
    """
    ydl_opts = {
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        # Save file into the uploads folder with its title
        'outtmpl': os.path.join(download_folder, '%(title)s.%(ext)s'),
        'quiet': True,
        'no_warnings': True,
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=True)
        # Get the filename generated by yt-dlp
        file_path = ydl.prepare_filename(info).rsplit('.', 1)[0] + ".mp3"
        file_name = info.get('title', 'Unknown Title')
        
        return file_name, file_path
